- src/locales/en.json
- src/views/CreateOrder.vue
#14
Showing toast mapping in case of wrong mapping or invalid SKU on uploading CSV to add items.
> Improved: showing error toast message when selecting wrong sku mapping (#14)

- src/components/OrderItemDetailActionsPopover.vue
- src/views/OrderDetail.vue
#22
- Fixed cancel alert showing when approving order.
- Ellipsis not opening issue in details page.
> Fixed: cancel alert in approved status and ellipsis opening issue (#22)

- src/store/modules/util/actions.ts
- src/utils/index.ts
- src/views/OrderDetail.vue
#24
Imporved UI of the shipments list in the order details page according to the figma.
Before
After
> Improved: UI of the shipments list in the order details page (#24)

- src/store/modules/util/actions.ts
- src/views/CreateOrder.vue
#21
Fixed unable to change carrier and shipment method for new order.
> Improved: sending the origin and destination facility contact mech while creation of order (#21)

- package-lock.json
- package.json
- src/views/CreateOrder.vue
- src/views/Transfers.vue
#32 
- Upgraded ionic/core, ionic/vue-router and ionic/vue to v8.4.2
- Added size to ion-button with icon inside
- Removed all the code added to fix infinite-scrolling in specific cases. If needed to revert this then change `main[part="scroll"]` to `div[part="scroll"]`.
> Improved: ionic version to 8.4.2(#32)

- src/views/CreateOrder.vue
#22
Fixed the condition for checking 0 ordered quantity validation.
> Fixed: validation for 0 ordered quantity (#22)

- src/locales/en.json
- src/views/CreateOrder.vue
#22
Fixed order being created with -ve ordered quantity.
> Fixed: order being created with -ve item ordered quantity (#22)

- src/views/Transfers.vue
#39
Added the "Sort by" label in the created by sorting button.
Before
After
> Fixed: added the missing Sort by label in the sorting by date button (#39)

- src/components/AddProductModal.vue
- src/services/OrderService.ts
#22
- Improved code to refetch the order item for the orderItemSeqId
- Fixed the incorrect updation of state on adding item.
- Creating item in created status instead of approved.
> Improved: refetching the newly added product for orderItemSeqId and fixed improper updation of state (#22)

- src/views/OrderDetail.vue
#31
Refactored facility address displaying logic to avoid falsy and null values.
> Improved: facility address displaying logic to avoid falsy values (#31)

- package-lock.json
- package.json
- src/components/ImportCsvModal.vue
#28
Using dxp to show dynamic good identification fetched from db for the identifier selector instead of hardcoded one in Import CSV modal.
> Improved: using dynamic good identification from db instead of hardcoding (#28)

- src/components/AddProductModal.vue
- src/services/OrderService.ts
- src/services/UtilService.ts
- src/store/modules/order/actions.ts
- src/utils/index.ts
- src/views/CreateOrder.vue
- src/views/OrderDetail.vue
#55
Added support for order item unit price while creation and showing it on detials page.
> Improved: support for order item price while creation and displaying on order details page (#55)

- package-lock.json
- package.json
- src/services/UtilService.ts
- src/store/modules/util/actions.ts
#9
- Used the already fetched `productIdentifierEnumId` field from the updated OMS API changes for the product stores.
> Improved: Used fetched global identifier from updated oms-api for fieldName in sample CSV (#9)

- src/views/OrderDetail.vue
#31
Updated the logic to display facility address for better UI visibility in case of missing info.
Before
After
> Fixed: incorrect displaying of facility address in case of missing fields (#31)

- package-lock.json
- package.json
> Updated: app version for minor release v1.1.0

- src/components/OrderItemDetailActionsPopover.vue
#62
Fixed issue in receiving transfer order item.
> Fixed: condition for getting shipment with current item for receiving (#62)

- package-lock.json
- package.json
> Updated: app version for patch release v1.1.1

- package-lock.json
- package.json
> Updated: app version for patch release v1.1.2

- src/services/OrderService.ts
#80 
Shifted the approveOrder status in OrderDetail page in Transfer-app to Moqui(#80 ).
> Improved:shifted approveOrder status to moqui

- src/services/OrderService.ts
- src/services/UtilService.ts
- src/store/modules/order/actions.ts
- src/store/modules/util/actions.ts
- src/views/OrderDetail.vue
#82 
Shifted Transfer order detail page of Transfer app into Moqui(#82 )
> Improved:Transfer_order_detail_to_moqui(#82)

- package-lock.json
- package.json
> Updated: app version for minor release v1.2.0.

- src/views/CreateOrder.vue
Improved  : modified the Payload in createorder service on createOrderPage
> Improved: modified the payload in createorder service
